name: ci-cd
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter codigo"
      - run: echo "Executar Testes"
      - run: echo "Build da Imagem"
      - run: push da imagem"
    
    
    
    
    
    
