name: ci-cd
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter codigo"
      - run: echo "Executar Testes"
      - run: echo "Build da Imagem"
      - run: echo "push da imagem"
    
  cd:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter codigo"
      - run: echo "configurar o kubeconfig"
      - run: echo "executar o apply da imagem"
    
    
    
    
    
